# MBG4181 Biyolojik Veri Analizi ve Görüntüleme

## Kaynaklar

- *R for Data Science*,  Hadley Wickham, Mine Cetinkaya-Rundel, Garrett Grolemund. 2.baskı, 2023  [link](https://r4ds.hadley.nz/)

## Ders1

*28 Eylül 2026 13:00* | **İçerik**: İlk derste, dönem boyunca kullanacağımız import-transform-model-communicate akışına genel bir bakış yapılacak. Tidyverse hakkında bilgi verilecektir. [Sunum linki](ders-intro.qmd)

## Ders2

*5 Ekim 2026 13:00* | **İçerik**: *unvotes* verisi üzerinde **select** ve **filter** komutları gösterildi. [Sunum linki](ders-select-filter.qmd)

## Ders3

*12 Ekim 2026 13:00* | **İçerik**: *unvotes* verisi üzerinde **mutate** ve **summarize** komutları gösterildi. [Sunum linki](ders-mutate-summarize.qmd)

## Ders4

*19 Ekim 2026 13:00* | **İçerik**: *unvotes* verisi üzerinde **mutate** ve **summarize** komutları gösterildi. [Sunum linki](ders-mutate-summarize.qmd) (Quiz1)

## Ders5

*26 Ekim 2026 13:000* | **İçerik**: Dosya okuma komutları gösterildi. [Sunum linki](ders-import.qmd)

## Ders6

*2 Kasım 2026 13:00* | **İçerik**: Tablo şeklini değiştirme (pivot) ve tablo birleştirme (join). [Sunum linki](ders-pivot-join.qmd)

## Ders7

*9 Kasım 2026 13:00* | **İçerik**: *ggplot* ile görselleştirme. [Sunum linki](ders-ggplot.qmd) (Quiz2)

## Vize1

*16 Kasım 2026*

## Ders8

*23 Kasım 2026 13:00* | **İçerik**: *ggplot* ile görselleştirme konusuna devam edildi. [Sunum linki](ders-ggplot.qmd)

## Ders9

*30 Kasım 2026 13:00* | **İçerik**: *quarto* veya *Rmarkdown* ile rapor, websayfası veya sunum oluşturma. [Sunum linki](ders-quarto.qmd) 

## Ders10

*7 Aralık 2026 13:00* | **İçerik**: *quarto* veya *Rmarkdown* ile rapor, websayfası veya sunum oluşturma. [Sunum linki](ders-quarto.qmd) (Quiz3-ggplot) (Homework: Please select a data, make sure that you can import it and sketch desired plots)

## Ders11

*14 Aralık 2026 13:00* | **İçerik**: *tidytext* ile doğal dil işleme. [Sunum linki](ders-tidytext.qmd) (Homework: minimum of 3 plots prepared with ggplot)

## Vize2

*21 Aralık 2026 13:00* 

## Ders12

*28 Aralık 2026 13:00* | **İçerik**: *tidygraph* ile ağ analizi. [Sunum linki](ders-tidygraph.qmd) (Quiz4)

## Ders13

*4 Ocak 2027 13:00* | **İçerik**: Ödev değerlendirme
